name = "polyroots-fortran"
author = "Jacob Williams"
copyright  = "Copyright (c) 2022, Jacob Williams"
license = "BSD-3"
description = "Polynomial Roots with Modern Fortran"
homepage = "https://github.com/jacobwilliams/polyroots-fortran"
keywords = ["root"]

[build]
auto-executables = false
auto-examples = false
auto-tests = true
link = ["lapack", "blas"]

[dependencies]
    mersenne-twister-fortran = { git="https://github.com/jacobwilliams/mersenne-twister-fortran.git", tag = "1.0.1" }

[dev-dependencies]
    pyplot-fortran = { git="https://github.com/jacobwilliams/pyplot-fortran.git", tag = "3.2.0" }

[library]
source-dir = "src"

[install]
library = true